server:
  port: 7104
spring:
  application:
    name: jzb-media
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    username: jzb
    password: AAAaaa111***
    url: jdbc:postgresql://127.0.0.1:9123/JDB_MEDIA
    driver-class-name: org.postgresql.Driver


mybatis:
  typeAliasesPackage: com.jzb.**.**.entity
  mapperLocations: classpath:/mapping/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7101/eureka/
  instance:
    prefer-ip-address: true

# 请求处理的超时时间 请求连接的超时时间
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000