server:
  port: 7501
spring:
  application:
    name: jzb-auth
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: jzb
    password: AAAaaa111***
    url: jdbc:postgresql://192.168.0.251:9123/JDB_AUTH
    driver-class-name: org.postgresql.Driver

mybatis:
  typeAliasesPackage: com.jzb.**.**.entity
  mapperLocations: classpath:/mapping/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7101/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.jzb.auth.dao.*: debug     #这是你的mapper包路径。

# 请求处理的超时时间 请求连接的超时时间
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000