server:
  port: 7505
spring:
  application:
    name: jzb-operate
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: jzb
    password: AAAaaa111***
    url: jdbc:postgresql://127.0.0.1:9123/JDB_OPT
    driver-class-name: org.postgresql.Driver

mybatis:
    typeAliasesPackage: com.jzb.**.**.entity
    mapperLocations: classpath:/mapping/*.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      call-setters-on-nulls: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7101/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.jzb.open.dao.*: debug     #这是你的mapper包路径。

# 请求处理的超时时间 请求连接的超时时间
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000