server:
  port: 7102

spring:
  application:
    name: jzb-oauth
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: jzb
    password: AAAaaa111***
    url: jdbc:postgresql://192.168.0.251:9123/jdb_auth
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  session:
    store-type: redis
  redis:
    database: 5
    host: 192.168.0.251
    port: 6100
    password: AAAaaa111***
    timeout: 3000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7101/eureka/
  instance:
    prefer-ip-address: true

mybatis:
  typeAliasesPackage: com.jzb.oauth.**.**.entity
  mapperLocations: classpath:/mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true

# 请求处理的超时时间 请求连接的超时时间
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000