server:
  port: 7105

spring:
  application:
    name: jzb-message
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: jzb
    password: AAAaaa111***
    url: jdbc:postgresql://192.168.0.251:9123/JDB_MSG
    driver-class-name: org.postgresql.Driver

mybatis:
    typeAliasesPackage: com.jzb.**.**.entity
    mapperLocations: classpath:/mapping/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7101/eureka/
  instance:
    prefer-ip-address: true

# 请求处理的超时时间 请求连接的超时时间
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000