server:
  port: 7103
spring:
  application:
    name: jzb-redis
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: application/x-www-form-urlencoded;charset=UTF-8
  redis:
    database: 0
    host: 192.168.0.251
    port: 6100
    password: AAAaaa111***
    timeout: 3000
    pool:
      max-wait: -1
      max-idle: 10
      min-idle: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7101/eureka/
  instance:
    prefer-ip-address: true

# 请求处理的超时时间 请求连接的超时时间
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000