server:
  port: 7506
spring:
  application:
    name: jzb-config
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: jzb
    password: AAAaaa111***
    url: jdbc:postgresql://47.92.247.137:9123/jdb_base
    driver-class-name: org.postgresql.Driver

  cloud:
    config:
      server:
        jdbc:
          sql: SELECT configkey, configvalue FROM tb_system_config WHERE application =? AND profile =? AND label =? AND status = '1'
      label: master
    refresh:
      refreshable: none
  profiles:
    active: jdbc


mybatis:
  typeAliasesPackage: com.jzb.**.**.entity
  mapperLocations: classpath:/mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7101/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.jzb.auth.dao.*: debug     #这是你的mapper包路径。

# 请求处理的超时时间 请求连接的超时时间
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000